name: scaffold
description: A scaffold that uses go_router, get_it and bloc and simplifies your life.
version: 0.0.1
homepage: https://github.com/wendellrocha/scaffold

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^7.5.0
  go_router: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
